from enum import Enum


class SessionAuction(Enum):
    CLOSED = 0
    TWOSIDED = 1
    OPENING = 2
    CLOSING = 3


class InstrumentType(Enum):
    STOCK = 0
    FUTURES = 1


class AccountType(Enum):
    ACCOUNT_TYPE_UNSPECIFIED = 0
    ACCOUNT_TYPE_TINKOFF = 1
    ACCOUNT_TYPE_TINKOFF_IIS = 2
    ACCOUNT_TYPE_INVEST_BOX = 3
    ACCOUNT_TYPE_INVEST_FUND = 4


class CandleInterval(Enum):
    CANDLE_INTERVAL_UNSPECIFIED = 0
    CANDLE_INTERVAL_1MIN = 1
    CANDLE_INTERVAL_5MIN = 2
    CANDLE_INTERVAL_15MIN = 3
    CANDLE_INTERVAL_HOUR = 4
    CANDLE_INTERVAL_DAY = 5
    CANDLE_INTERVAL_2MIN = 6
    CANDLE_INTERVAL_3MIN = 7
    CANDLE_INTERVAL_10MIN = 8
    CANDLE_INTERVAL_30MIN = 9
    CANDLE_INTERVAL_2_HOUR = 10
    CANDLE_INTERVAL_4_HOUR = 11
    CANDLE_INTERVAL_WEEK = 12
    CANDLE_INTERVAL_MONTH = 13